USE [master]
GO

/****** Object:  Database [bifconvenio]    Script Date: 10-Jan-23 11:59:04 AM ******/
CREATE DATABASE [bifconvenio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BIFConvenios_Data', FILENAME = N'D:\BaseDatos\bifconveniox.mdf' , SIZE = 5919104KB , MAXSIZE = UNLIMITED, FILEGROWTH = 80KB )
 LOG ON 
( NAME = N'BIFConvenios_Log', FILENAME = N'D:\BaseDatos\bifconvenio_log.ldf' , SIZE = 2377088KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [bifconvenio] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bifconvenio].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [bifconvenio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bifconvenio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bifconvenio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bifconvenio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bifconvenio] SET ARITHABORT OFF 
GO

ALTER DATABASE [bifconvenio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bifconvenio] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [bifconvenio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bifconvenio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bifconvenio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bifconvenio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bifconvenio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bifconvenio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bifconvenio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bifconvenio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bifconvenio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bifconvenio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bifconvenio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bifconvenio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bifconvenio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bifconvenio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bifconvenio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bifconvenio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bifconvenio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bifconvenio] SET  MULTI_USER 
GO

ALTER DATABASE [bifconvenio] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [bifconvenio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bifconvenio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bifconvenio] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [bifconvenio] SET  READ_WRITE 
GO


